README.md:
	touch README.md
	echo "Unix Workbench GitHub repository assignment" >> README.md
	date +"%A %d %B %Y %T" >> README.md
	echo "There are $(wc -l $guessingame.sh) lines of code in the bash script." >> README.md 
